#TOTAL_MEMORY=67108864
#TOTAL_MEMORY=209715200
#TOTAL_MEMORY=419430400
TOTAL_MEMORY=1048576000
EM_PRELOAD_FLAGS = \
	--preload-file "$(SYSROOT)@/"

#CXXFLAGS += $(INCLUDES) \
             --std=c++17 -Wall -MD \
			 -s USE_SDL=2 -s USE_SDL_TTF=2 -s USE_SDL_IMAGE=2 \
			 -s USE_WEBGL2=1 \
			 -s ERROR_ON_UNDEFINED_SYMBOLS=0 \
			 -s TOTAL_MEMORY=$(TOTAL_MEMORY) \
			 -s OFFSCREEN_FRAMEBUFFER=1 \
			 -O2 $(SHADER_FLAGS)
			 #-Os -g
			 #-s FULL_ES3=1

%.html: %.o
	$(CXX) $(OBJ) $(CXXFLAGS) $(EM_PRELOAD_FLAGS) -o $@ 
